###
# @name loginAdmin
post http://localhost:5000/auth
Content-Type: application/json

{
    "login": "admin",
    "password": "admin1234"
}

###
# login user1
post http://localhost:5000/auth
Content-Type: application/json

{
    "login": "user1",
    "password": "1234"
}

###
# get user
get http://localhost:5000/user/iel
Authorization: Bearer {{loginAdmin.response.body.$.token}}

###
# create user
post http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer {{loginAdmin.response.body.$.token}}

{
    "name": "User1",
    "login": "user1",
    "password": "1234",
    "claims": [
        { "type": "Permission", "value": "CreateTransaction" },
        { "type": "Permission", "value": "ListTransaction" }
    ]
}
