###
# @name login
post http://localhost:5000/auth
Content-Type: application/json

{
    "login": "user1",
    "password": "1234"
}

###
# get user
get http://localhost:5001/entry?begin=2022-01-01&end=2022-11-29Z&offset=0
Authorization: Bearer {{login.response.body.$.token}}

###
# create user
post http://localhost:5001/entry
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
    "amount": 100,
    "description": "Something"
}
